<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFrameworks>net480</TargetFrameworks>
        <UseWPF>true</UseWPF>
        <PlatformTarget>x64</PlatformTarget>
        <RootNamespace>CugaScript</RootNamespace>
        <StartupObject>CugaScript.App</StartupObject>
        <ApplicationIcon>Assets\Images\CugaScript.ico</ApplicationIcon>
        <InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);Microsoft.Extensions.Configuration.Binder.SourceGeneration</InterceptorsPreviewNamespaces>
    </PropertyGroup>

    <PropertyGroup>
        <ContentSQLiteInteropFiles>true</ContentSQLiteInteropFiles>
        <CopySQLiteInteropFiles>false</CopySQLiteInteropFiles>
        <CleanSQLiteInteropFiles>false</CleanSQLiteInteropFiles>
        <CollectSQLiteInteropFiles>false</CollectSQLiteInteropFiles>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <PackageReference Include="System.Data.SQLite.Core" />
        <PackageReference Include="FreeSql.Provider.Sqlite" />
        <PackageReference Include="NLog.Schema" />
        <PackageReference Include="NLog.Extensions.Hosting" />
        <PackageReference Include="MrAdvice" />
        <PackageReference Include="SourceGenerator.InjectHostDI">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0'">
        <PackageReference Include="Mapster" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net480'">
        <PackageReference Include="Mapster" VersionOverride="7.3.0" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="halcondotnetxl">
            <HintPath>..\..\..\Depends\semix.arithmetic\halcondotnetxl.dll</HintPath>
        </Reference>
        <Reference Include="HAlgorithm">
            <HintPath>..\..\..\Depends\semix.arithmetic\calibration\HAlgorithm.dll</HintPath>
        </Reference>
        <Reference Include="Semix.CoreLib">
            <HintPath>..\..\..\Depends\semix.corelib\Semix.CoreLib.dll</HintPath>
        </Reference>
        <Reference Include="Semix.WcfTransfer.DTO">
            <HintPath>..\..\..\Depends\semix.runtime\Semix.WcfTransfer.DTO.dll</HintPath>
        </Reference>
        <Reference Include="Semix.WcfTransfer.Interfaces">
            <HintPath>..\..\..\Depends\semix.runtime\Semix.WcfTransfer.Interfaces.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cores\Core.Services\Core.Services.csproj" />
        <ProjectReference Include="..\Databases\Local.NoSQL.DB.Providers\Local.NoSQL.DB.Providers.csproj" />
        <ProjectReference Include="..\Databases\Local.SQL.DB.Providers\Local.SQL.DB.Providers.csproj" />
        <ProjectReference Include="..\Utilities\Net.Utilities.Roslyn.Build\Net.Utilities.Roslyn.Build.csproj" />
        <ProjectReference Include="..\Utilities\Net.Utilities.WPF.MVVM\Net.Utilities.WPF.MVVM.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\Cuga-Calibration-Solution\Core\**\*.cs">
            <Link>Core\%(RecursiveDir)\%(Filename)%(Extension)</Link>
        </Compile>
        <Page Include="..\Cuga-Calibration-Solution\Views\LoadingWindow.xaml">
            <Link>Views\%(Filename)%(Extension)</Link>
        </Page>
        <Compile Include="..\Cuga-Calibration-Solution\Views\LoadingWindow.xaml.cs">
            <Link>Views\%(Filename)%(Extension)</Link>
        </Compile>
        <Page Include="..\Cuga-Calibration-Solution\Views\LoginWindow.xaml">
            <Link>Views\%(Filename)%(Extension)</Link>
        </Page>
        <Compile Include="..\Cuga-Calibration-Solution\Views\LoginWindow.xaml.cs">
            <Link>Views\%(Filename)%(Extension)</Link>
        </Compile>
        <Page Include="..\Cuga-Calibration-Solution\Views\Common\Windows\View\*.xaml">
            <Link>Views\Common\Windows\View\%(Filename)%(Extension)</Link>
        </Page>
        <Compile Include="..\Cuga-Calibration-Solution\Views\Common\Windows\View\*.cs">
            <Link>Views\Common\Windows\View\%(Filename)%(Extension)</Link>
        </Compile>

        <Compile Include="..\Cuga-Calibration-Solution\ViewModels\LoadingWindowViewModel.cs">
            <Link>ViewModels\%(Filename)%(Extension)</Link>
        </Compile>
        <Compile Include="..\Cuga-Calibration-Solution\ViewModels\LoginWindowViewModel.cs">
            <Link>ViewModels\%(Filename)%(Extension)</Link>
        </Compile>
        <Compile Include="..\Cuga-Calibration-Solution\ViewModels\Common\*.cs">
            <Link>ViewModels\Common\%(Filename)%(Extension)</Link>
        </Compile>
        <Compile Include="..\Cuga-Calibration-Solution\ViewModels\Common\Windows\View\*.cs">
            <Link>ViewModels\Common\Windows\View\%(Filename)%(Extension)</Link>
        </Compile>

        <Compile Remove="..\Cuga-Calibration-Solution\Core\ApplicationProvider.cs" />

        <Compile Remove="..\Cuga-Calibration-Solution\Core\Converters\MultiValueEqualityManageViewModelConverter.cs" />
        <Compile Remove="..\Cuga-Calibration-Solution\Core\Converters\MultiValueEqualityViewModelConverter.cs" />
    </ItemGroup>

    <ItemGroup>
        <ApplicationDefinition Remove="App.xaml" />
        <Page Include="App.xaml" />
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="appsettings.Development.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <DependentUpon>appsettings.json</DependentUpon>
        </Content>
        <Content Include="appsettings.Production.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <DependentUpon>appsettings.json</DependentUpon>
        </Content>
        <Content Include="..\Cuga-Calibration-Solution\NLog.config">
            <Link>%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Assets\Images\*.*" />
        <Resource Include="..\Cuga-Calibration-Solution\Assets\Images\*.*">
            <Link>Assets\Images\%(Filename)%(Extension)</Link>
        </Resource>
        <None Include="..\Cuga-Calibration-Solution\Assets\Data\*.*">
            <Link>Assets\Data\%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>