<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net480;net8.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Databases\Local.NoSQL.DB.Providers\Local.NoSQL.DB.Providers.csproj" />
        <ProjectReference Include="..\..\Databases\Local.SQL.DB.Providers\Local.SQL.DB.Providers.csproj" />
        <ProjectReference Include="..\Core.Wcf\Core.Wcf.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="halcondotnetxl">
            <HintPath>..\..\Dependencies\Halcon\halcondotnetxl.dll</HintPath>
        </Reference>
    </ItemGroup>
    
    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
        <PackageReference Include="Semix.CoreLib" />
        <PackageReference Include="Semix.GRPC.DTO" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net480'">
        <Reference Include="Semix.CoreLib">
            <HintPath>..\..\Dependencies\Semix.Cuga.Runtime2.0\Semix.CoreLib.dll</HintPath>
        </Reference>
        <Reference Include="Semix.WcfTransfer.DTO">
            <HintPath>..\..\Dependencies\Semix.Cuga.Runtime2.0\Semix.WcfTransfer.DTO.dll</HintPath>
        </Reference>
        <Reference Include="Cuga.Data.DataStruct">
            <HintPath>..\..\Dependencies\Semix.Cuga.Runtime2.0\Cuga.Data.DataStruct.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>