<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net48;net10.0-windows10.0.19041</TargetFrameworks>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Net.Utilities.WPF.Behaviors.Calibration\Net.Utilities.WPF.Behaviors.Calibration.csproj" />
        <ProjectReference Include="..\Net.Utilities.WPF.Commands.Calibration\Net.Utilities.WPF.Commands.Calibration.csproj" />
    </ItemGroup>

</Project>
