using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace Net.Utilities.SourceGenerators.Calibration;

[Generator(LanguageNames.CSharp)]
public sealed class CacheSourceGenerator : IIncrementalGenerator
{
    public const string DefaultCacheAttributeFullName = "Net.Utilities.SourceGenerators.Calibration.Attributes.DefaultCacheAttribute";
    public const string RecipeCacheAttributeFullName = "Net.Utilities.SourceGenerators.Calibration.Attributes.RecipeCacheAttribute";

    private const string AttributeSourceCode = """
                                               // <auto-generated />
                                               #nullable enable

                                               namespace Net.Utilities.SourceGenerators.Calibration.Attributes
                                               {
                                                   [global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
                                                   internal sealed class DefaultCacheAttribute : global::System.Attribute
                                                   {
                                                       public DefaultCacheAttribute() { }
                                                   }

                                                   [global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
                                                   internal sealed class RecipeCacheAttribute : global::System.Attribute
                                                   {
                                                       public RecipeCacheAttribute() { }
                                                   }
                                               }
                                               """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource(
                "SourceGenerators.CacheAttributes.g.cs",
                SourceText.From(AttributeSourceCode, Encoding.UTF8)));

        var defaultCacheTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: DefaultCacheAttributeFullName,
                predicate: static (node, _) => node is PropertyDeclarationSyntax or VariableDeclaratorSyntax,
                transform: static (ctx, _) => GetArguments(ctx))
            .Where(static item => string.IsNullOrWhiteSpace(item.Type) == false)
            .Collect();

        var recipeCacheTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: RecipeCacheAttributeFullName,
                predicate: static (node, _) => node is PropertyDeclarationSyntax or VariableDeclaratorSyntax,
                transform: static (ctx, _) => GetArguments(ctx))
            .Where(static item => string.IsNullOrWhiteSpace(item.Type) == false)
            .Collect();

        var assemblyName = context.CompilationProvider
            .Select(static (c, _) => c.Assembly.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat));

        var combined = defaultCacheTypes
            .Combine(recipeCacheTypes)
            .Combine(assemblyName);

        context.RegisterSourceOutput(combined, static (ctx, source) =>
        {
            var ((defaultCaches, recipeCaches), assemblyName) = source;

            var code = GenerateSource(assemblyName, defaultCaches, recipeCaches);
            ctx.AddSource(
                "SourceGenerators.CacheCollector.g.cs",
                SourceText.From(code, Encoding.UTF8));
        });
    }

    private static (string Type, bool IsArray) GetArguments(GeneratorAttributeSyntaxContext context)
    {
        var typeSymbol = context.TargetSymbol switch
        {
            IPropertySymbol propertySymbol => propertySymbol.Type,
            IFieldSymbol fieldSymbol => fieldSymbol.Type,
            _ => null
        };

        if (typeSymbol is null) return (string.Empty, false);

        var isArray = typeSymbol.Kind == SymbolKind.ArrayType;
        if (isArray && typeSymbol is IArrayTypeSymbol arraySymbol) typeSymbol = arraySymbol.ElementType;

        return (typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), isArray);
    }

    private static string GenerateSource(
        string assemblyName,
        ImmutableArray<(string Type, bool IsArray)> defaultCaches,
        ImmutableArray<(string Type, bool IsArray)> recipeCaches)
    {
        var pascalAssemblyName = SourceGeneratorHelper.ToPascalCaseName(assemblyName);

        var defaultCacheContent = string.Join("\n", defaultCaches
            .Distinct()
            .OrderBy(t => t.Type)
            .Select(t => $"            (typeof({t.Type}), {t.IsArray.ToString().ToLower()}),"));

        var recipeCacheContent = string.Join("\n", recipeCaches
            .Distinct()
            .OrderBy(t => t.Type)
            .Select(t => $"            (typeof({t.Type}), {t.IsArray.ToString().ToLower()}),"));

        return $$"""
                 // <auto-generated />
                 #nullable enable

                 namespace Net.Utilities.SourceGenerators.Calibration
                 {
                     public static class {{pascalAssemblyName}}CacheCollector
                     {
                         public static readonly (global::System.Type Type, bool IsArray)[] DefaultCaches =
                         [
                 {{defaultCacheContent}}
                         ];

                         public static readonly (global::System.Type Type, bool IsArray)[] RecipeCaches =
                         [
                 {{recipeCacheContent}}
                         ];
                     }
                 }
                 """;
    }
}