using Core.Models.Enums.Optics;

namespace Core.Models.Models.Common.Status.Behaviours;

public class OpticsIlluminationModeCalibrationStatusListBoxSelectedItemBehavior : CalibrationStatusListBoxSelectedItemBehavior<OpticsIlluminationModeCalibrationStatus, OpticsIlluminationModeEnum>;