using Core.Models.Models.Common.Pattern;

namespace Core.Models.Models.Common.Status.Behaviours;

public class ProductivityInformationCalibrationStatusListBoxSelectedItemBehavior : CalibrationStatusListBoxSelectedItemBehavior<ProductivityInformationCalibrationStatus, ProductivityInformation>;