<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net480;net8.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Net.Utilities.IOC" />
        <PackageReference Include="Yitter.IdGenerator" />
        <PackageReference Include="FreeSql" />
        <PackageReference Include="FreeSql.Repository" />
        <PackageReference Include="SourceGenerator.InjectHostDI">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>