using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace Core.Utilities.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class CacheSourceGenerator : IIncrementalGenerator
{
    private const string DefaultCacheAttributeFullName = "Core.Utilities.SourceGenerators.Attributes.DefaultCacheAttribute";
    private const string RecipeCacheAttributeFullName = "Core.Utilities.SourceGenerators.Attributes.RecipeCacheAttribute";

    private const string AttributeSourceCode = """
                                               // <auto-generated />
                                               #nullable enable

                                               namespace Core.Utilities.SourceGenerators.Attributes
                                               {
                                                   [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
                                                   internal sealed class DefaultCacheAttribute : global::System.Attribute
                                                   {
                                                       public DefaultCacheAttribute(global::System.Type type, bool isArray = false) { }
                                                   }

                                                   [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
                                                   internal sealed class RecipeCacheAttribute : global::System.Attribute
                                                   {
                                                       public RecipeCacheAttribute(global::System.Type type, bool isArray = false) { }
                                                   }
                                               }
                                               """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("SourceGenerators.CacheAttributes.g.cs", SourceText.From(AttributeSourceCode, Encoding.UTF8)));

        var defaultCacheTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: DefaultCacheAttributeFullName,
                predicate: static (node, _) => IsTargetClass(node),
                transform: static (ctx, _) => GetAttributeArguments(ctx, DefaultCacheAttributeFullName))
            .SelectMany(static (items, _) => items)
            .Collect();

        var recipeCacheTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: RecipeCacheAttributeFullName,
                predicate: static (node, _) => IsTargetClass(node),
                transform: static (ctx, _) => GetAttributeArguments(ctx, RecipeCacheAttributeFullName))
            .SelectMany(static (items, _) => items)
            .Collect();

        var combined = defaultCacheTypes.Combine(recipeCacheTypes);

        context.RegisterSourceOutput(combined, static (ctx, source) =>
        {
            var (defaultCaches, recipeCaches) = source;
            ctx.AddSource("SourceGenerators.CacheCollector.g.cs", SourceText.From(GenerateCacheCollector(defaultCaches, recipeCaches), Encoding.UTF8));
        });
    }

    private static bool IsTargetClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDeclaration
               && classDeclaration.Modifiers.Any(SyntaxKind.AbstractKeyword) == false
               && classDeclaration.Modifiers.Any(SyntaxKind.StaticKeyword) == false;
    }

    private static ImmutableArray<(string Type, bool IsArray)> GetAttributeArguments(GeneratorAttributeSyntaxContext context, string attributeFullName)
    {
        var items = ImmutableArray.CreateBuilder<(string Type, bool IsArray)>();

        foreach (var attribute in context.Attributes.Where(attribute => attribute.AttributeClass?.ToDisplayString() == attributeFullName))
        {
            if (attribute.ConstructorArguments[0].Value is ITypeSymbol typeSymbol &&
                attribute.ConstructorArguments[1].Value is bool isArray)
            {
                items.Add((typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), isArray));
            }
        }

        return items.ToImmutable();
    }

    private static string GenerateCacheCollector(ImmutableArray<(string Type, bool IsArray)> defaultCaches, ImmutableArray<(string Type, bool IsArray)> recipeCaches)
    {
        var defaultCacheContent = string.Join("\n", defaultCaches.Distinct().OrderBy(t => t.Type).Select(t => $"            new CacheItem(typeof({t.Type}), {t.IsArray.ToString().ToLower()}),"));
        var recipeCacheContent = string.Join("\n", recipeCaches.Distinct().OrderBy(t => t.Type).Select(t => $"            new CacheItem(typeof({t.Type}), {t.IsArray.ToString().ToLower()}),"));

        return $$"""
                 // <auto-generated />
                 #nullable enable

                 namespace Core.Utilities
                 {
                     public static class CacheCollector
                     {
                         public record struct CacheItem(global::System.Type Type, bool IsArray);

                         public static readonly CacheItem[] DefaultCaches = new CacheItem[]
                         {
                 {{defaultCacheContent}}
                         };

                         public static readonly CacheItem[] RecipeCaches = new CacheItem[]
                         {
                 {{recipeCacheContent}}
                         };
                     }
                 }
                 """;
    }
}