using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;

namespace Core.Utilities.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class CacheSourceGenerator : IIncrementalGenerator
{
    private const string DefaultCacheAttributeFullName = "Core.Utilities.SourceGenerators.Attributes.DefaultCacheAttribute";
    private const string RecipeCacheAttributeFullName = "Core.Utilities.SourceGenerators.Attributes.RecipeCacheAttribute";

    private const string AttributeSourceCode = """
                                               // <auto-generated />
                                               #nullable enable

                                               namespace Core.Utilities.SourceGenerators.Attributes
                                               {
                                                   [global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
                                                   public sealed class DefaultCacheAttribute : global::System.Attribute
                                                   {
                                                       public DefaultCacheAttribute() { }
                                                   }

                                                   [global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
                                                   public sealed class RecipeCacheAttribute : global::System.Attribute
                                                   {
                                                       public RecipeCacheAttribute() { }
                                                   }
                                               }
                                               """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("SourceGenerators.CacheAttributes.g.cs", SourceText.From(AttributeSourceCode, Encoding.UTF8)));

        var defaultCacheTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: DefaultCacheAttributeFullName,
                predicate: static (node, _) => node is PropertyDeclarationSyntax or VariableDeclaratorSyntax,
                transform: static (ctx, _) => GetArguments(ctx))
            .Where(static item => string.IsNullOrWhiteSpace(item.Type) == false)
            .Collect();

        var recipeCacheTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: RecipeCacheAttributeFullName,
                predicate: static (node, _) => node is PropertyDeclarationSyntax or VariableDeclaratorSyntax,
                transform: static (ctx, _) => GetArguments(ctx))
            .Where(static item => string.IsNullOrWhiteSpace(item.Type) == false)
            .Collect();

        var combined = defaultCacheTypes
            .Combine(recipeCacheTypes)
            .Combine(context.CompilationProvider);

        context.RegisterSourceOutput(combined, static (ctx, source) =>
        {
            var ((defaultCaches, recipeCaches), compilation) = source;

            var assemblyName = compilation.AssemblyName ?? "Unknown";
            var safeAssemblyName = Regex.Replace(assemblyName, @"[^a-zA-Z0-9.]", "");
            safeAssemblyName = Regex.Replace(safeAssemblyName, @"^\d+", "");

            var code = GenerateProjectCacheCollector(safeAssemblyName, defaultCaches, recipeCaches);
            ctx.AddSource("SourceGenerators.CacheCollector.g.cs", SourceText.From(code, Encoding.UTF8));
        });
    }

    private static (string Type, bool IsArray) GetArguments(GeneratorAttributeSyntaxContext context)
    {
        var typeSymbol = context.TargetSymbol switch
        {
            IPropertySymbol propertySymbol => propertySymbol.Type,
            IFieldSymbol fieldSymbol => fieldSymbol.Type,
            _ => null
        };

        if (typeSymbol is null) return (string.Empty, false);

        var isArray = typeSymbol.Kind == SymbolKind.ArrayType;
        if (isArray && typeSymbol is IArrayTypeSymbol arraySymbol) typeSymbol = arraySymbol.ElementType;

        return (typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), isArray);
    }

    /// <summary>
    /// 生成项目特定命名空间的 CacheCollector
    /// </summary>
    private static string GenerateProjectCacheCollector(
        string projectName,
        ImmutableArray<(string Type, bool IsArray)> defaultCaches,
        ImmutableArray<(string Type, bool IsArray)> recipeCaches)
    {
        var defaultCacheContent = string.Join("\n", defaultCaches
            .Distinct()
            .OrderBy(t => t.Type)
            .Select(t => $"            new CacheItem(typeof({t.Type}), {t.IsArray.ToString().ToLower()}),"));

        var recipeCacheContent = string.Join("\n", recipeCaches
            .Distinct()
            .OrderBy(t => t.Type)
            .Select(t => $"            new CacheItem(typeof({t.Type}), {t.IsArray.ToString().ToLower()}),"));

        return $$"""
                 // <auto-generated />
                 #nullable enable

                 namespace {{projectName}}
                 {
                     /// <summary>
                     /// Cache collector for {{projectName}} project
                     /// </summary>
                     public static class CacheCollector
                     {
                         public readonly record struct CacheItem(global::System.Type Type, bool IsArray);

                         public static readonly CacheItem[] DefaultCaches = new CacheItem[]
                         {
                 {{defaultCacheContent}}
                         };

                         public static readonly CacheItem[] RecipeCaches = new CacheItem[]
                         {
                 {{recipeCacheContent}}
                         };
                         
                         public static global::System.Collections.Generic.IEnumerable<(global::System.Type Type, bool IsArray)> GetDefaultCachesAsEnumerable()
                         {
                             foreach (var item in DefaultCaches)
                             {
                                 yield return (item.Type, item.IsArray);
                             }
                         }
                         
                         public static global::System.Collections.Generic.IEnumerable<(global::System.Type Type, bool IsArray)> GetRecipeCachesAsEnumerable()
                         {
                             foreach (var item in RecipeCaches)
                             {
                                 yield return (item.Type, item.IsArray);
                             }
                         }
                     }
                 }
                 """;
    }
}