using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Core.Utilities.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class PermissionGenerator : IIncrementalGenerator
{
    private const string PermissionControlAttributeFullName = "Core.Utilities.SourceGenerators.Attributes.PermissionAttribute";

    private const string AttributeSourceCode = """
                                               // <auto-generated />
                                               #nullable enable

                                               namespace Core.Utilities.SourceGenerators.Attributes
                                               {
                                                   [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                                                   internal sealed class PermissionAttribute : global::System.Attribute
                                                   {
                                                   }
                                               }
                                               """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("SourceGenerators.PermissionAttribute.g.cs", SourceText.From(AttributeSourceCode, Encoding.UTF8)));

        var classDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: PermissionControlAttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax classDeclaration
                                               && classDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword)
                                               && classDeclaration.Modifiers.Any(SyntaxKind.AbstractKeyword) == false
                                               && classDeclaration.Modifiers.Any(SyntaxKind.StaticKeyword) == false
                                               && classDeclaration.Parent is BaseNamespaceDeclarationSyntax,
                transform: static (ctx, _) => SemanticTransform(ctx))
            .Where(static info => info is not null);

        context.RegisterSourceOutput(classDeclarations, static (ctx, classInfo) =>
        {
            if (classInfo is null) return;

            ctx.AddSource($"{classInfo.ClassName}.Permission.g.cs", SourceText.From(GeneratePartialClass(classInfo), Encoding.UTF8));
        });
    }

    private static ClassInfo? SemanticTransform(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol classSymbol) return null;

        var baseType = classSymbol.BaseType;
        while (baseType is not null)
        {
            var fullName = baseType.ToDisplayString();
            if (fullName
                is "System.Windows.FrameworkElement"
                or "System.Windows.Controls.UserControl"
                or "System.Windows.Controls.Control"
                or "System.Windows.Window")
            {
                return new ClassInfo(
                    classSymbol.ContainingNamespace.ToDisplayString(),
                    classSymbol.Name);
            }

            baseType = baseType.BaseType;
        }

        return null;
    }

    private static string GeneratePartialClass(ClassInfo classInfo)
    {
        return $$"""
                 // <auto-generated/>

                 #nullable enable

                 namespace {{classInfo.Namespace}};

                 partial class {{classInfo.ClassName}}
                 {
                     private void InitializePermissionControl()
                     {
                         this.Loaded += OnPermissionControlLoaded;
                     }

                     private void OnPermissionControlLoaded(object sender, System.Windows.RoutedEventArgs e)
                     {
                         this.Loaded -= OnPermissionControlLoaded;
                         
                         global::CugaCalibration.Core.Permission.PermissionHelper.ApplyPermissions(this);
                     }
                 }
                 """;
    }


    private sealed record ClassInfo(string Namespace, string ClassName);
}