<Project>

    <PropertyGroup>
        <RepositoryDirectory>$([System.IO.Path]::GetDirectoryName($(MSBuildThisFileDirectory.TrimEnd('\'))))</RepositoryDirectory>
        <BuildToolsDirectory>$(RepositoryDirectory)\Build</BuildToolsDirectory>
        <SolutionDirectory>$(SolutionDir.TrimEnd('\'))</SolutionDirectory>
    </PropertyGroup>

    <Import Project="$(BuildToolsDirectory)\Common.Build.props" />

    <PropertyGroup>
        <LangVersion>12.0</LangVersion>
        <Version>2.1.0705</Version>
        <AssemblyVersion>2.1.0.0705</AssemblyVersion>
        <FileVersion>2.1.0.0705</FileVersion>
    </PropertyGroup>

</Project>