<Project>

    <PropertyGroup>
        <RepositoryDirectory>$([System.IO.Path]::GetDirectoryName($(MSBuildThisFileDirectory.TrimEnd('\'))))</RepositoryDirectory>
        <BuildToolsDirectory>$(RepositoryDirectory)\Build</BuildToolsDirectory>
        <SolutionDirectory>$(SolutionDir.TrimEnd('\'))</SolutionDirectory>

        <GitType>GitLab</GitType>
        <GitURL>http://192.168.0.28:8099/semix/software/publiclibraries/common/Net.Utilities</GitURL>
    </PropertyGroup>

    <Import Project="$(BuildToolsDirectory)\Common.Build.props" />

    <PropertyGroup>
        <Version>2.5.0413</Version>
        <AssemblyVersion>2.5.2.0413</AssemblyVersion>
        <FileVersion>2.5.2.0413</FileVersion>
    </PropertyGroup>

</Project>