<Project>

    <Target Name="CopyToBuild"
            BeforeTargets="BeforeBuild"
            Condition="'$(RunOnceTarget)' == 'true'">
        <!-- Git -->
        <Copy
            SourceFiles="$(BuildToolsDirectory)\.gitattributes"
            DestinationFiles="$(RepositoryDirectory)\.gitattributes" />
        <Message Importance="high" Text="========== Copy .gitattributes OK! ==========" />
        <Copy
            SourceFiles="$(BuildToolsDirectory)\.gitignore"
            DestinationFiles="$(RepositoryDirectory)\.gitignore" />
        <Message Importance="high" Text="========== Copy .gitignore OK! ==========" />
        <Copy
            SourceFiles="$(BuildToolsDirectory)\LICENSE.txt"
            DestinationFiles="$(RepositoryDirectory)\LICENSE.txt" />
        <Message Importance="high" Text="========== Copy LICENSE.txt OK! ==========" />
        <!-- Git -->
        <!-- Solution Format -->
        <Copy
            SourceFiles="$(BuildToolsDirectory)\.csharpierrc.json"
            DestinationFiles="$(SolutionDirectory)\.csharpierrc.json" />
        <Message Importance="high" Text="========== Copy .csharpierrc.json OK! ==========" />
        <Copy
            SourceFiles="$(BuildToolsDirectory)\.editorconfig"
            DestinationFiles="$(SolutionDirectory)\.editorconfig" />
        <Message Importance="high" Text="========== Copy .editorconfig OK! ==========" />
        <Copy
            SourceFiles="$(BuildToolsDirectory)\ignored-misspelling.dic"
            DestinationFiles="$(SolutionDirectory)\ignored-misspelling.dic" />
        <Message Importance="high" Text="========== Copy ignored-misspelling.dic OK! ==========" />
        <Copy
            SourceFiles="$(BuildToolsDirectory)\Settings.XamlStyler"
            DestinationFiles="$(SolutionDirectory)\Settings.XamlStyler" />
        <Message Importance="high" Text="========== Copy Settings.XamlStyler OK! ==========" />
        <!-- Solution Format -->
    </Target>

</Project>