<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net48;net10.0</TargetFrameworks>
        <Nullable>disable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <AssemblyName>Cuga.Calibration.Core.Wcf</AssemblyName>
        <RootNamespace>Core.Wcf</RootNamespace>
    </PropertyGroup>

    <Import Project="$(BuildToolsDirectory)\Nuget.Build.props" />

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
        <PackageReference Include="Cuga.Interface" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
        <Reference Include="Cuga.Data.DataStruct">
            <HintPath>$(RepositoryDirectory)\Dependencies\Semix.Cuga.Runtime2.0\Cuga.Data.DataStruct.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Using Remove="Polyfills" />
        <Using Remove="System.Net.Http" />
    </ItemGroup>

</Project>