<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net480;net8.0</TargetFrameworks>
        <AssemblyName>Cuga.Calibration.Core.Wcf</AssemblyName>
        <RootNamespace>Core.Wcf</RootNamespace>
    </PropertyGroup>

    <Import Project="$(BuildToolsDirectory)\Nuget.Build.props" />

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
        <PackageReference Include="Cuga.Interface" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net480'">
        <Reference Include="Cuga.Data.DataStruct">
            <HintPath>..\..\..\Dependencies\Semix.Cuga.Runtime2.0\Cuga.Data.DataStruct.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>