<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net480;net8.0</TargetFrameworks>
        <AssemblyName>Core.Utilities</AssemblyName>
        <RootNamespace>Core.Utilities</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FreeSql" />
        <PackageReference Include="FreeSql.Repository" />
        <PackageReference Include="FreeSql.Provider.Sqlite" />
        <PackageReference Include="morelinq" />

		<PackageReference Include="Net.Utilities.Mapper" />
        <PackageReference Include="Net.Utilities.Models" />
        <PackageReference Include="Net.Utilities.DataAnnotations" />
        <PackageReference Include="Net.Utilities.Helpers" />
        <PackageReference Include="Net.Utilities.Algorithms" />
        <PackageReference Include="Net.Utilities.Algorithms.Halcon" />
        <PackageReference Include="Net.Utilities.IOC" />

        <PackageReference Include="Net.Utilities.Nlog" />

        <PackageReference Include="Net.Utilities.Graphics" />

        <PackageReference Include="Local.NoSQL.DB.Providers" />
        <PackageReference Include="Local.SQL.DB.Providers" />
    </ItemGroup>

</Project>