<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net480;net8.0</TargetFrameworks>
        <AssemblyName>Core.Utilities</AssemblyName>
        <RootNamespace>Core.Utilities</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Net.Utilities.Mapper" VersionOverride="3.30.1-preview3.30-hanqi" />
        <PackageReference Include="Net.Utilities.Models" VersionOverride="3.30.1-preview3.30-hanqi" />
        <PackageReference Include="Net.Utilities.DataAnnotations" VersionOverride="3.30.1-preview3.30-hanqi" />
        <PackageReference Include="Net.Utilities.Helpers" VersionOverride="3.30.1-preview3.30-hanqi" />
        <PackageReference Include="Net.Utilities.Algorithms" VersionOverride="3.30.1-preview3.30-hanqi" />
        <PackageReference Include="Net.Utilities.Algorithms.Halcon" VersionOverride="3.30.1-preview3.30-hanqi" />
        <PackageReference Include="Net.Utilities.IOC" VersionOverride="3.30.1-preview3.30-hanqi" />

        <PackageReference Include="Net.Utilities.Nlog" VersionOverride="3.30.1-preview3.30-hanqi" />

        <PackageReference Include="Net.Utilities.Graphics" VersionOverride="3.30.1-preview3.30-hanqi" />
        <PackageReference Include="Net.Utilities.Graphics.Algorithms.Halcon" VersionOverride="3.30.1-preview3.30-hanqi" />

        <PackageReference Include="Local.SQL.Cache.Providers" VersionOverride="3.30.1-preview3.30-hanqi" />
        <PackageReference Include="Local.SQL.DB.Providers" VersionOverride="3.30.1-preview3.30-hanqi" />
    </ItemGroup>

</Project>