<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net480;net8.0</TargetFrameworks>
        <AssemblyName>Core.Utilities</AssemblyName>
        <RootNamespace>Core.Utilities</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Net.Utilities.Mapper" VersionOverride="2.6.1-preview2.3-xuan" />
        <PackageReference Include="Net.Utilities.Models" VersionOverride="2.6.1-preview2.3-xuan" />
        <PackageReference Include="Net.Utilities.DataAnnotations" VersionOverride="2.6.1-preview2.3-xuan" />
        <PackageReference Include="Net.Utilities.Helpers" VersionOverride="2.6.1-preview2.3-xuan" />
        <PackageReference Include="Net.Utilities.Algorithms" VersionOverride="2.6.1-preview2.3-xuan" />
        <PackageReference Include="Net.Utilities.Algorithms.Halcon" VersionOverride="2.6.1-preview2.3-xuan" />
        <PackageReference Include="Net.Utilities.IOC" VersionOverride="2.6.1-preview2.3-xuan" />

        <PackageReference Include="Net.Utilities.Nlog" VersionOverride="2.6.1-preview2.3-xuan" />

        <PackageReference Include="Net.Utilities.Graphics" VersionOverride="2.6.1-preview2.3-xuan" />
        <PackageReference Include="Net.Utilities.Graphics.Algorithms.Halcon" VersionOverride="2.6.1-preview2.3-xuan" />

        <PackageReference Include="Local.SQL.Cache.Providers" VersionOverride="2.6.1-preview2.3-xuan" />
        <PackageReference Include="Local.SQL.DB.Providers" VersionOverride="2.6.1-preview2.3-xuan" />
    </ItemGroup>

</Project>