// <auto-generated />
#if !NETCOREAPP && !NETSTANDARD2_1_OR_GREATER

namespace System.Collections.Generic;

using System;
using System.Collections.Generic;
using System.ComponentModel;

public static class KeyValuePairExtensions
{
    extension<TKey, TValue>(KeyValuePair<TKey, TValue> @this)
    {
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.keyvaluepair-2.deconstruct?view=net-10.0
        [EditorBrowsable(EditorBrowsableState.Never)]
        public void Deconstruct(out TKey key, out TValue value)
        {
            key = @this.Key;
            value = @this.Value;
        }
    }
}
#endif