<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net48;net10.0-windows10.0.19041</TargetFrameworks>
        <UseWPF>true</UseWPF>
        <AssemblyName>Net.Utilities.WPF.Behaviors.Calibration</AssemblyName>
        <RootNamespace>$(AssemblyName)</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Net.Utilities.WPF.Converters.Calibration\01. Net.Utilities.WPF.Converters.Calibration.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="DataGridScrollToCurrentBehavior.cs" />
      <Compile Remove="ComboBoxSelectedItemBehavior.cs" />
      <Compile Remove="ListBoxSelectedItemsBehavior.cs" />
      <Compile Remove="SelectorAutoSelectFirstBehavior.cs" />
    </ItemGroup>
    
</Project>
