<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net480;net8.0-windows10.0.19041</TargetFrameworks>
        <UseWPF>true</UseWPF>
        <AssemblyName>Core.Utilities.WPF</AssemblyName>
        <RootNamespace>Core.Utilities.WPF</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Net.Utilities.ImageViewer.WPF" VersionOverride="2.8.1-preview8.0-xuan" />
        <PackageReference Include="Net.Utilities.OpticsFourierImageViewer.WPF" VersionOverride="2.8.1-preview8.0-xuan" />
        <PackageReference Include="Net.Utilities.WaferMap.WPF" VersionOverride="2.8.1-preview8.0-xuan" />
        <PackageReference Include="Net.Utilities.ScottPlot.WPF" VersionOverride="2.8.1-preview8.0-xuan" />
        <PackageReference Include="Net.Utilities.Graphics.WPF" VersionOverride="2.8.1-preview8.0-xuan" />

        <PackageReference Include="Net.Utilities.WPF" VersionOverride="2.8.1-preview8.0-xuan" />
        <PackageReference Include="Net.Utilities.WPF.MVVM" VersionOverride="2.8.1-preview8.0-xuan" />
        <PackageReference Include="WPF.CanvasViewer" VersionOverride="2.8.1-preview8.0-xuan" />

        <PackageReference Include="WPF.CustomControl" VersionOverride="2.8.1-preview8.0-xuan" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Core.Utilities\00. Core.Utilities.csproj" />
    </ItemGroup>

</Project>