<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net480;net10.0-windows10.0.19041</TargetFrameworks>
        <UseWPF>true</UseWPF>
        <AssemblyName>Core.Utilities.WPF</AssemblyName>
        <RootNamespace>Core.Utilities.WPF</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Net.Utilities.ImageViewer.WPF" />
        <PackageReference Include="Net.Utilities.OpticsFourierImageViewer.WPF" />
        <PackageReference Include="Net.Utilities.WaferMap.WPF" />
        <PackageReference Include="Net.Utilities.ScottPlot.WPF" />
        <PackageReference Include="Net.Utilities.ScottPlot" />
        <PackageReference Include="Net.Utilities.ScottPlot.WPF.V2" />
        <PackageReference Include="Net.Utilities.Graphics.WPF" />

        <PackageReference Include="Net.Utilities.WPF" />
        <PackageReference Include="Net.Utilities.WPF.MVVM" />
        <PackageReference Include="WPF.CanvasViewer" />

        <PackageReference Include="WPF.CustomControl" />

        <PackageReference Include="Microsoft.Web.WebView2" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Assets\Css\*.css" />
        <EmbeddedResource Include="Assets\Js\*.js" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Core.Utilities\00. Core.Utilities.csproj" />
    </ItemGroup>

</Project>