<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net48;net10.0</TargetFrameworks>
        <AssemblyName>Net.Utilities.Calibration</AssemblyName>
        <RootNamespace>$(AssemblyName)</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="algocv_sharp" VersionOverride="1.0.10" />

        <PackageReference Include="Net.Utilities.Mapper" VersionOverride="2.9.5-preview7-xuan" />
        <PackageReference Include="Net.Utilities.Models" VersionOverride="2.9.5-preview7-xuan" />
        <PackageReference Include="Net.Utilities.DataAnnotations" VersionOverride="2.9.5-preview7-xuan" />
        <PackageReference Include="Net.Utilities.Helpers" VersionOverride="2.9.5-preview7-xuan" />
        <PackageReference Include="Net.Utilities.Algorithms" VersionOverride="2.9.5-preview7-xuan" />
        <PackageReference Include="Net.Utilities.Algorithms.Halcon" VersionOverride="2.9.5-preview7-xuan" />
        <PackageReference Include="Net.Utilities.IOC" VersionOverride="2.9.5-preview7-xuan" />

        <PackageReference Include="Net.Utilities.Nlog" VersionOverride="2.9.5-preview7-xuan" />

        <PackageReference Include="Net.Utilities.Graphics" VersionOverride="2.9.5-preview7-xuan" />
        <PackageReference Include="Net.Utilities.Graphics.Algorithms.Halcon" VersionOverride="2.9.5-preview7-xuan" />

        <PackageReference Include="Local.SQL.Cache.Providers" VersionOverride="2.9.5-preview7-xuan" />
        <PackageReference Include="Local.SQL.DB.Providers" VersionOverride="2.9.5-preview7-xuan" />
    </ItemGroup>

</Project>