<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>

        <Features>strict</Features>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <AnalysisLevel>latest</AnalysisLevel>
        <!-- 禁用生成输出程序集打包不打包到 .nupkg 文件中报警 -->
        <NoWarn>$(NoWarn);NU5128</NoWarn>

        <Version>1.7.2</Version>
        <AssemblyVersion>1.7.2.0</AssemblyVersion>
        <FileVersion>1.7.2.0</FileVersion>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>SourceGenerator.AssemblyMetadata</PackageId>
        <PackageIcon>SourceGenerator.AssemblyMetadata.png</PackageIcon>
        <PackageTags>Source Generator, Assembly Metadata</PackageTags>
        <PackageReleaseNotes>If you have questions, please submit issue.</PackageReleaseNotes>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageProjectUrl>https://github.com/xkz1994/SourceGenerator.Test</PackageProjectUrl>

        <Title>SourceGenerator.AssemblyMetadata</Title>
        <Authors>Kaizhi Xuan</Authors>
        <Owners>Kaizhi Xuan</Owners>
        <Company>Kaizhi Xuan</Company>
        <Product>SourceGenerator.AssemblyMetadata</Product>
        <Description>SourceGenerator.AssemblyMetadata</Description>
        <Copyright>Copyright © 2024.Kaizhi Xuan</Copyright>

        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RepositoryUrl>https://github.com/xkz1994/SourceGenerator.Test</RepositoryUrl>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <RepositoryType>Github</RepositoryType>
        <!--~1~ 源代码的路径不正确不需要 @1@
        ~1~ https://github.com/dotnet/sourcelink/#using-sourcelink @1@
        <ContinuousIntegrationBuild Condition=" '$(GITHUB_ACTIONS)' == 'true' ">True</ContinuousIntegrationBuild>-->

        <IsPackable>true</IsPackable>
        <!--~1~ Roslyn不需要 @1@
        ~1~ 创建符号包 @1@
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>-->
        <!-- 构建系统将未由源代码管理跟踪或未从源包导入到生成的 PDB 的项目源文件嵌入 -->
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <!-- 在生成期间自动生成包 -->
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

        <!-- Roslyn 需要的 -->
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>
        <!-- 此布尔值指定是否应将生成输出程序集打包到 .nupkg 文件中 -->
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <!-- 用户生成私有PrivateAssets -->
        <DevelopmentDependency>true</DevelopmentDependency>
        <!-- Roslyn 不需要符号包 -->
        <IncludeSymbols>false</IncludeSymbols>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <!--~1~ 源代码的路径不正确不需要 @1@
        <PackageReference Include="Microsoft.SourceLink.GitHub">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>-->
    </ItemGroup>

    <ItemGroup>
        <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/roslyn4.10/cs" Visible="false" />
    </ItemGroup>

    <ItemGroup>
        <None Include="SourceGenerator.AssemblyMetadata.png" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>