<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net480;net8.0-windows10.0.19041</TargetFrameworks>
		<UseWPF>true</UseWPF>
		<AssemblyName>Core.Recipe</AssemblyName>
		<RootNamespace>Core.Recipe</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="SourceGenerator.InjectHostDI">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net480'">
        <Reference Include="Semix.CoreLib">
            <HintPath>..\..\..\Dependencies\Semix.Cuga.Runtime2.0\Semix.CoreLib.dll</HintPath>
        </Reference>
        <Reference Include="Semix.WcfTransfer.DTO">
            <HintPath>..\..\..\Dependencies\Semix.Cuga.Runtime2.0\Semix.WcfTransfer.DTO.dll</HintPath>
        </Reference>
        <Reference Include="Cuga.Data.DataStruct">
            <HintPath>..\..\..\Dependencies\Semix.Cuga.Runtime2.0\Cuga.Data.DataStruct.dll</HintPath>
        </Reference>
    </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core.Utilities\00. Core.Utilities.csproj" />
		<ProjectReference Include="..\Core.Models\04. Core.Models.csproj" />
	</ItemGroup>

</Project>
