using Core.Models.Models.Common.Pattern;

namespace Core.Models.Models.Common.Status.Behaviors;

public sealed class ListBoxSelectedItemProductivityInformationAndLaserLightInformationStatusBehavior : ListBoxSelectedItemStatusBehavior<ProductivityInformationAndLaserLightInformationStatus, ProductivityInformation>;