using Core.Models.Enums.Optics;

namespace Core.Models.Models.Common.Status.Behaviors;

public sealed class OpticsIlluminationModeAndProductivityInformationListBoxSelectedItemStatusBehavior : ListBoxSelectedItemStatusBehavior<OpticsIlluminationModeAndProductivityInformationStatus, OpticsIlluminationModeEnum>;