using Core.Models.Enums.Optics;
using Core.Models.Models.Common.Pattern;

namespace Core.Models.Models.Common.Status.Behaviors;

public sealed class OpticsIlluminationModeAndProductivityInformationAndApodizationCalibrationStatusListBoxSelectedItemBehavior : CalibrationStatusListBoxSelectedItemBehavior<OpticsIlluminationModeAndProductivityInformationAndApodizationCalibrationStatus, OpticsIlluminationModeEnum>;

public sealed class ProductivityInformationAndApodizationCalibrationStatusListBoxSelectedItemBehavior : CalibrationStatusListBoxSelectedItemBehavior<ProductivityInformationAndApodizationCalibrationStatus, ProductivityInformation>;

public sealed class OpticsApodizationModeCalibrationStatusListBoxSelectedItemBehavior : CalibrationStatusListBoxSelectedItemBehavior<OpticsApodizationModeCalibrationStatus, OpticsApodizationModeEnum>;