using Core.Models.Enums.Optics;

namespace Core.Models.Models.Common.Status.Behaviors;

public sealed class OpticsIlluminationModeAndProductivityInformationCalibrationStatusListBoxSelectedItemBehavior : CalibrationStatusListBoxSelectedItemBehavior<OpticsIlluminationModeAndProductivityInformationCalibrationStatus, OpticsIlluminationModeEnum>;