using Core.Models.Models.Common.Pattern;

namespace Core.Models.Models.Common.Status.Behaviors;

public class ProductivityInformationCalibrationStatusListBoxSelectedItemBehavior : CalibrationStatusListBoxSelectedItemBehavior<ProductivityInformationCalibrationStatus, ProductivityInformation>;