<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFrameworks>net48;net10.0-windows10.0.19041</TargetFrameworks>
        <UseWPF>true</UseWPF>
        <RootNamespace>CugaCalibration</RootNamespace>
        <ApplicationIcon>Assets\Images\CugaCalibration.ico</ApplicationIcon>

        <Platform>x64</Platform>
        <Platforms>x64</Platforms>
        <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <PropertyGroup>
        <ContentSQLiteInteropFiles>true</ContentSQLiteInteropFiles>
        <CopySQLiteInteropFiles>false</CopySQLiteInteropFiles>
        <CleanSQLiteInteropFiles>false</CleanSQLiteInteropFiles>
        <CollectSQLiteInteropFiles>false</CollectSQLiteInteropFiles>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <PackageReference Include="NLog.Extensions.Hosting" />
        <PackageReference Include="R3" />
        <PackageReference Include="System.Data.SQLite.Core" />
        <PackageReference Include="FreeSql.Provider.Sqlite" />
        <PackageReference Include="pythonnet" />
        <PackageReference Include="SourceGenerator.InjectHostDI">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="HAlgorithm">
            <HintPath>$(RepositoryDirectory)\Dependencies\HAlgorithm.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
        <Reference Include="Semix.CoreLib">
            <HintPath>$(RepositoryDirectory)\Dependencies\Semix.Cuga.Runtime2.0\Semix.CoreLib.dll</HintPath>
        </Reference>
        <Reference Include="Cuga.Data.DataStruct">
            <HintPath>$(RepositoryDirectory)\Dependencies\Semix.Cuga.Runtime2.0\Cuga.Data.DataStruct.dll</HintPath>
        </Reference>
        <Reference Include="Semix.WcfTransfer.DTO">
            <HintPath>$(RepositoryDirectory)\Dependencies\Semix.Cuga.Runtime2.0\Semix.WcfTransfer.DTO.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\Dependencies\Semix.Cuga.Runtime2.0\libalgocv.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Visible>false</Visible>
        </Content>
        <Content Include="..\..\Dependencies\Semix.Cuga.Runtime2.0\libstdc++-6.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Visible>false</Visible>
        </Content>
        <Content Include="..\..\Dependencies\Semix.Cuga.Runtime2.0\libwinpthread-1.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Visible>false</Visible>
        </Content>
        <Content Include="..\..\Dependencies\Semix.Cuga.Runtime2.0\libgcc_s_seh-1.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Visible>false</Visible>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Net.Utilities\Net.Utilities.SourceGenerators.Calibration\Net.Utilities.SourceGenerators.Calibration.csproj" PrivateAssets="all" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\Cores\Core.Services\03. Core.Services.csproj" />
        <ProjectReference Include="..\Cores\Core.Recipe\04. Core.Recipe.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Core\Services\Interfaces\IApplicationCookieService.*.cs">
            <DependentUpon>IApplicationCookieService.cs</DependentUpon>
        </Compile>
        <Compile Update="Core\Services\Implements\ApplicationCookieServiceImpl.*.cs">
            <DependentUpon>ApplicationCookieServiceImpl.cs</DependentUpon>
        </Compile>
        <Compile Update="ViewModels\CalibrationViewModelBase.*.cs">
            <DependentUpon>CalibrationViewModelBase.cs</DependentUpon>
        </Compile>
        <Compile Update="ViewModels\MainWindowViewModel.*.cs">
            <DependentUpon>MainWindowViewModel.cs</DependentUpon>
        </Compile>
        <Compile Update="ViewModels\Common\Windows\Tools\AODWaveform\AODWaveform*.cs">
            <DependentUpon>$([System.Text.RegularExpressions.Regex]::Replace('%(Filename)', '^(AODWaveform(?:Common|ElectrodeOffset|ElectrodeInitialize)).*', 'Abstract$1WindowViewModel.cs'))</DependentUpon>
        </Compile>
        <Compile Update="ViewModels\Common\Windows\Tools\AODWaveform\ChirpAODWaveform*.cs;ViewModels\Common\Windows\Tools\AODWaveform\PrescanAODWaveform*.cs">
            <DependentUpon>$([System.Text.RegularExpressions.Regex]::Replace('%(Filename)', '^((?:Chirp|Prescan)AODWaveform(?:ElectrodeOffset|ElectrodeInitialize|Training)).*', '$1WindowViewModel.cs'))</DependentUpon>
        </Compile>
        <Compile Update="ViewModels\*\*.LoadDepends.cs">
            <DependentUpon>$([System.String]::Copy('%(Filename)').Replace('.LoadDepends', '.cs'))</DependentUpon>
        </Compile>
        <Compile Update="ViewModels\Common\Windows\Tools\CIB\CIBAging*.cs">
            <DependentUpon>CIBAgingWindowViewModel.cs</DependentUpon>
        </Compile>
        <Compile Update="ViewModels\Common\Windows\Tools\Optics\OpticsGrabbingImage*.cs">
            <DependentUpon>OpticsGrabbingImageWindowViewModel.cs</DependentUpon>
        </Compile>
        <Compile Update="ViewModels\Common\Windows\Tools\Optics\OpticsBestFocus*.cs">
            <DependentUpon>OpticsBestFocusWindowViewModel.cs</DependentUpon>
        </Compile>
        <Compile Update="ViewModels\Common\Windows\Tools\Stage\StageMap*.cs">
            <DependentUpon>StageMapWindowViewModel.cs</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <ApplicationDefinition Remove="App.xaml" />
        <Page Include="App.xaml" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="appsettings.Development.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <DependentUpon>appsettings.json</DependentUpon>
        </Content>
        <Content Include="appsettings.Production.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <DependentUpon>appsettings.json</DependentUpon>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Content Include="NLog.config">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>

        <None Remove="Assets\Python\*.*" />
        <EmbeddedResource Include="Assets\Python\*.*" />

        <None Remove="Assets\Images\*.*" />
        <Resource Include="Assets\Images\*.*" />
    </ItemGroup>

</Project>