<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFrameworks>net480;net8.0-windows</TargetFrameworks>
        <UseWPF>true</UseWPF>
        <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net480'">
        <PackageReference Include="Grpc.Core" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0-windows'">
        <PackageReference Include="Grpc.Net.Client" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Utilities\Net.Utilities.WPF\Net.Utilities.WPF.csproj" />
        <ProjectReference Include="..\GRPC.CodeFirst.Shared\GRPC.CodeFirst.Shared.csproj" />
    </ItemGroup>

</Project>