<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net480;net10.0-windows10.0.19041</TargetFrameworks>
        <UseWPF>true</UseWPF>
        <AssemblyName>Core.Services</AssemblyName>
        <RootNamespace>Core.Services</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SourceGenerator.InjectHostDI">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows10.0.19041'">
        <PackageReference Include="Grpc.Net.Client" />
        <PackageReference Include="Semix.CoreLib.Grpc" />
        <PackageReference Include="Cuga.Interface" />
        <PackageReference Include="protobuf-net" />
        <PackageReference Include="protobuf-net.Grpc" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net480'">
        <Reference Include="System.ServiceModel" />
        <Reference Include="System.Net.Http" />
        <Reference Include="Semix.WcfTransfer.Interfaces">
            <HintPath>..\..\..\Dependencies\Semix.Cuga.Runtime2.0\Semix.WcfTransfer.Interfaces.dll</HintPath>
        </Reference>
        <Reference Include="Cuga.Agent.EngineBase">
            <HintPath>..\..\..\Dependencies\Semix.Cuga.Runtime2.0\Cuga.Agent.EngineBase.dll</HintPath>
        </Reference>
        <Reference Include="Cuga.Engine.Interface">
            <HintPath>..\..\..\Dependencies\Semix.Cuga.Runtime2.0\Cuga.Engine.Interface.dll</HintPath>
        </Reference>
        <Reference Include="Semix.CoreLib">
            <HintPath>..\..\..\Dependencies\Semix.Cuga.Runtime2.0\Semix.CoreLib.dll</HintPath>
        </Reference>
        <Reference Include="Semix.WcfTransfer.DTO">
            <HintPath>..\..\..\Dependencies\Semix.Cuga.Runtime2.0\Semix.WcfTransfer.DTO.dll</HintPath>
        </Reference>
        <Reference Include="Cuga.Data.DataStruct">
            <HintPath>..\..\..\Dependencies\Semix.Cuga.Runtime2.0\Cuga.Data.DataStruct.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Core.Models\04. Core.Models.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows10.0.19041'">
        <Compile Remove="Implements\Wcf\*.cs" />
        <None Include="Implements\Wcf\*.cs" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net480'">
        <Compile Remove="Implements\Grpc\*.cs" />
        <None Include="Implements\Grpc\*.cs" />
    </ItemGroup>

</Project>