using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Core.SourceGenerators;

/// <summary>
/// Permission 权限控制 Source Generator
/// 为标记了 [PermissionControl] 的 UserControl 类自动生成权限检查代码
/// </summary>
[Generator(LanguageNames.CSharp)]
public class PermissionGenerator : IIncrementalGenerator
{
    private const string PermissionControlAttributeFullName = "Core.SourceGenerators.Attributes.PermissionControlAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. 注入 Attribute 源代码，使其可被消费项目使用
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("PermissionControlAttribute.g.cs", SourceText.From(AttributeSourceCode, Encoding.UTF8)));

        // 2. 创建管道：筛选带有 [PermissionControl] 特性的类
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateClass(node),
                transform: static (ctx, _) => GetClassInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        // 3. 收集并生成代码
        context.RegisterSourceOutput(classDeclarations, static (ctx, classInfo) =>
        {
            var source = GeneratePartialClass(classInfo);
            ctx.AddSource($"{classInfo.ClassName}.Permission.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    /// <summary>
    /// 初步筛选：是否是类声明且带有特性
    /// </summary>
    private static bool IsCandidateClass(SyntaxNode node) =>
        node is ClassDeclarationSyntax { AttributeLists.Count: > 0 } classDeclaration
        && classDeclaration.Modifiers.Any(m => m.Text == "partial");

    /// <summary>
    /// 语义分析：获取类信息
    /// </summary>
    private static ClassInfo? GetClassInfo(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;

        // 获取类符号
        if (semanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
            return null;

        // 检查是否有 PermissionControl 特性
        var hasPermissionAttribute = classSymbol.GetAttributes()
            .Any(attr => attr.AttributeClass?.ToDisplayString() == PermissionControlAttributeFullName);

        if (!hasPermissionAttribute)
            return null;

        // 检查是否继承自 FrameworkElement（UserControl 的基类）
        if (!InheritsFromFrameworkElement(classSymbol))
            return null;

        return new ClassInfo(
            classSymbol.ContainingNamespace.ToDisplayString(),
            classSymbol.Name,
            classSymbol.IsSealed);
    }

    /// <summary>
    /// 检查类型是否继承自 FrameworkElement
    /// </summary>
    private static bool InheritsFromFrameworkElement(INamedTypeSymbol classSymbol)
    {
        var baseType = classSymbol.BaseType;
        while (baseType is not null)
        {
            var fullName = baseType.ToDisplayString();
            if (fullName is "System.Windows.FrameworkElement"
                         or "System.Windows.Controls.UserControl"
                         or "System.Windows.Controls.Control"
                         or "System.Windows.Window")
            {
                return true;
            }
            baseType = baseType.BaseType;
        }
        return false;
    }

    /// <summary>
    /// 生成 partial class 代码
    /// </summary>
    private static string GeneratePartialClass(ClassInfo classInfo)
    {
        var namespaceDeclaration = string.IsNullOrEmpty(classInfo.Namespace)
            ? ""
            : $"namespace {classInfo.Namespace};\n\n";

        return $$"""
            // <auto-generated />
            // This file was generated by Core.SourceGenerators.PermissionGenerator
            // Do not edit this file manually.

            #nullable enable

            {{namespaceDeclaration}}partial class {{classInfo.ClassName}}
            {
                /// <summary>
                /// 初始化权限控制（由 Source Generator 自动生成）
                /// 在构造函数中调用 InitializeComponent() 之后调用此方法
                /// </summary>
                private void InitializePermissionControl()
                {
                    this.Loaded += OnPermissionControlLoaded;
                }

                /// <summary>
                /// Loaded 事件处理程序，应用权限控制
                /// </summary>
                private void OnPermissionControlLoaded(object sender, System.Windows.RoutedEventArgs e)
                {
                    // 避免重复执行
                    this.Loaded -= OnPermissionControlLoaded;

                    // 应用权限控制
                    global::CugaCalibration.Core.Permission.PermissionHelper.ApplyPermissions(this);
                }
            }
            """;
    }

    /// <summary>
    /// Attribute 源代码 - 在编译时注入
    /// </summary>
    private const string AttributeSourceCode = """
        // <auto-generated />
        #nullable enable

        namespace Core.SourceGenerators.Attributes
        {
            /// <summary>
            /// 标记需要权限控制的 UserControl。
            /// Source Generator 将自动生成权限检查代码。
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            internal sealed class PermissionControlAttribute : global::System.Attribute
            {
            }
        }
        """;

    /// <summary>
    /// 类信息结构
    /// </summary>
    private readonly record struct ClassInfo(string Namespace, string ClassName, bool IsSealed);
}
